name: Trivy Image Scanning

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: vigneshviky7
#          password: dckr_pat_6g2hc0QF9ExrX7PZDiRQP7gBIzo
      
      - name: docker build
        uses: docker/build-push-action@v3
        with:
          run: docker build -t myapp:latest .
          
      - name: run as root for image pick   
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/tmp/.cache/ aquasec/trivy:0.10.0 myapp:latest
          
#      - name: Docker Push
#        run: docker push my-app:latest
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:latest'
          format: 'sarif'
          output: 'trivy-dims-scan-report.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-dims-scan-report.sarif'
