name: stackhawk Image Scanning

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: myapp-image  
    
      - name: Save Docker Image as Tarball
        run: |
          docker save -o myapp-image.tar myapp
          ls -lh myapp-image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-image
          path: myapp-image.tar
          
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: myapp-image
          path: /tmp/myapp-image.tar

      - name: Load Docker Image
        run: docker load -i /tmp/myapp-image.tar
          
      - name: Run tests 
        run: docker run -p 8080:80 -d myapp-image
                     
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
