name: stackhawk Image Scanning

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
                 
      - name: Run tests 
        run: docker run -p 8080:80 -d dockerbogo/docker-nginx-hello-world
                     
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
