name: CI

on:
  push:
    branches:
      - master
      
jobs:
  app-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run App Setup
        uses: favedom-dev/github-reusable-workflow/.github/workflows/app-setup.yaml@master
        with:
          OVERRIDE_NAME: pw-dims

  repo-version:
    needs: app-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Repo Version
        uses: favedom-dev/github-reusable-workflow/.github/workflows/repo-version.yaml@master
        with:
          MONOREPO_APP: ${{ needs.app-setup.outputs.NAME }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  sast-scan:
    needs: [app-setup, repo-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run SAST Scan
        uses: iamparuthi/docker-nginx-hello-world/.github/workflows/main.yml@master
        with:
          NAME: ${{ needs.app-setup.outputs.NAME }}
          VERSION: ${{ needs.repo-version.outputs.version }}
